# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-03-25 18:37
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Actor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombreLargo', models.CharField(max_length=50)),
                ('nombreCorto', models.CharField(max_length=5)),
                ('descripcion', models.TextField(max_length=500)),
            ],
            options={
                'verbose_name': 'Actor',
                'verbose_name_plural': 'Actores',
            },
        ),
        migrations.CreateModel(
            name='Estudio_Mactor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('descripcion', models.TextField()),
                ('fecha_inicio', models.DateField(default=django.utils.timezone.now)),
                ('fecha_final', models.DateField(default=django.utils.timezone.now)),
                ('estado', models.BooleanField(default=True)),
                ('idProyecto', models.PositiveIntegerField(default=1)),
                ('idAdministrador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mactor_administrador', to=settings.AUTH_USER_MODEL, verbose_name='administrador')),
                ('idCoordinador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mactor_coordinador', to=settings.AUTH_USER_MODEL, verbose_name='coordinador')),
                ('idExpertos', models.ManyToManyField(related_name='mactor_expertos_set', to=settings.AUTH_USER_MODEL, verbose_name='Expertos')),
            ],
            options={
                'verbose_name': 'Estudio_Mactor',
                'verbose_name_plural': 'Estudios_Mactor',
            },
        ),
        migrations.CreateModel(
            name='Ficha',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estrategia', models.TextField(blank=True, null=True)),
                ('idActorX', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='mactor_actorX_ficha', to='mactor.Actor')),
                ('idActorY', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='mactor_actorY_ficha', to='mactor.Actor')),
            ],
            options={
                'verbose_name': 'Ficha',
                'verbose_name_plural': 'Fichas',
            },
        ),
        migrations.CreateModel(
            name='Informe_Final',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField(auto_now=True)),
                ('informe', models.TextField()),
                ('estado', models.BooleanField(default=False)),
                ('idEstudio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mactor.Estudio_Mactor')),
            ],
            options={
                'verbose_name': 'Informe_final',
                'verbose_name_plural': 'Informes_finales',
            },
        ),
        migrations.CreateModel(
            name='Objetivo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombreLargo', models.CharField(max_length=50)),
                ('nombreCorto', models.CharField(max_length=5)),
                ('descripcion', models.TextField(max_length=500)),
                ('idEstudio', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='mactor.Estudio_Mactor')),
            ],
            options={
                'verbose_name': 'Objetivo',
                'verbose_name_plural': 'Objetivos',
            },
        ),
        migrations.CreateModel(
            name='Relacion_MAO',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.IntegerField(blank=True, null=True)),
                ('valor', models.IntegerField()),
                ('justificacion', models.TextField()),
                ('idActorY', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mactor.Actor')),
                ('idExperto', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('idObjetivoX', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mactor.Objetivo')),
            ],
            options={
                'verbose_name': 'Relacion_MAO',
                'verbose_name_plural': 'Relaciones_MAO',
            },
        ),
        migrations.CreateModel(
            name='Relacion_MID',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor', models.IntegerField()),
                ('justificacion', models.TextField()),
                ('idActorX', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='mactor_actorX_set', to='mactor.Actor')),
                ('idActorY', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='mactor_actorY_set', to='mactor.Actor')),
                ('idExperto', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Relacion_de_Influencia',
                'verbose_name_plural': 'Relaciones_de_influencia',
            },
        ),
        migrations.AddField(
            model_name='actor',
            name='idEstudio',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='mactor.Estudio_Mactor'),
        ),
        migrations.AlterUniqueTogether(
            name='relacion_mid',
            unique_together=set([('idActorX', 'idActorY', 'idExperto')]),
        ),
        migrations.AlterUniqueTogether(
            name='relacion_mao',
            unique_together=set([('tipo', 'idActorY', 'idObjetivoX', 'idExperto')]),
        ),
        migrations.AlterUniqueTogether(
            name='ficha',
            unique_together=set([('idActorY', 'idActorX')]),
        ),
    ]
