# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-09-26 22:26
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mactor', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='informe_final',
            name='idEstudio',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mactor.Estudio_Mactor'),
        ),
        migrations.AlterField(
            model_name='relacion_mao',
            name='idEstudio',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mactor.Estudio_Mactor'),
        ),
    ]
