# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-09-27 01:48
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mactor', '0002_auto_20170926_1726'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='estudio_mactor',
            name='idAdmin',
        ),
    ]
