# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-09-27 20:05
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mactor', '0003_remove_estudio_mactor_idadmin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actor',
            name='idEstudio',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='mactor.Estudio_Mactor'),
        ),
        migrations.AlterField(
            model_name='objetivo',
            name='idEstudio',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='mactor.Estudio_Mactor'),
        ),
    ]
